package utils

const MONGO_USERNAME = "MONGO_USERNAME"
const MONGO_PASSWORD = "MONGO_PASSWORD"
const MONGO_URI = "MONGO_URI"
const DATABASE = "DATABASE"
const USER_COLLECTION = "USER_COLLECTION"
const SCHEMA_COLLECTION = "SCHEMA_COLLECTION"
const DATA_COLLECTION = "DATA_COLLECTION"
const TASK_COLLECTION = "TASK_COLLECTION"

const SESSION_KEY_PREFIX = "ssk_"
const SCHEMA_KEY_PREFIX = "sk_"

const CONTEXT_CURRENT_USER = "currentUser"