package utils

const MONGO_USERNAME = "MONGO_USERNAME"
const MONGO_PASSWORD = "MONGO_PASSWORD"
const MONGO_URI = "MONGO_URI"
const DATABASE = "DATABASE"
const USER_COLLECTION = "USER_COLLECTION"
const SCHEMA_COLLECTION = "SCHEMA_COLLECTION"
const DATA_COLLECTION = "DATA_COLLECTION"
const TASK_COLLECTION = "TASK_COLLECTION"

const SESSION_KEY_PREFIX = "ssk_"
const SCHEMA_KEY_PREFIX = "sk_"

const CONTEXT_CURRENT_USER = "currentUser"

const SHEETS_SERVICE_ACCOUNT_KEY_PATH = "SHEETS_SERVICE_ACCOUNT_KEY_PATH"

//https://docs.google.com/spreadsheets/d/1ouDk9gxAWQ2gs8iyQVSRCVvmjd8fHwQHn8mNtA7dMa0/edit#gid=1802608806
const MASTER_SHEET = "MASTER_SHEET"
const USER_SHEET = "USER_SHEET"
const TASK_SHEET = "TASK_SHEET"